name: Deploy Snapshot (Master)

on:
  push:
    branches:
      - master

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: Deploy Snapshot
        run: ./gradlew :kakao:publishDefaultPublicationToOSSHRRepository --stacktrace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
