name: PR
on: [ pull_request ]
jobs:
  detekt:
    runs-on: ubuntu-latest
    name: Detekt
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: detekt
        run: |
          ./gradlew clean detekt

  assemble-debug-apk:
    needs: [ detekt ]
    name: Assemble Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble Debug APK
        run: bash ./gradlew sample:assembleDebug
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: sample/build/outputs/apk/debug/sample-debug.apk

  assemble-debug-android-test-apk:
    needs: [ detekt ]
    name: Assemble Instrumental APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble Instrumental APK
        run: bash ./gradlew sample:assembleDebugAndroidTest
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk

  firebase-lab-test:
    needs: [ assemble-debug-apk, assemble-debug-android-test-apk ]
    name: Firebase Instrumental API
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api: [ 30 ]
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Run tests on Firebase Test Lab for ${{ matrix.api }}
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: .github/firebase/devices-specs.yml:api-${{ matrix.api }}
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_TESTLAB_JSON }}
