name: sample-connected-checks
on: [ pull_request ]
jobs:
  integration-test:
    runs-on: macOS-10.15
    strategy:
      fail-fast: false
      matrix:
        api: [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: connectedCheck
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
        timeout-minutes: 30
        with:
          cmd: ./gradlew connectedCheck
          cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -cores 2 -memory 3072 -no-window -gpu swiftshader_indirect
          api: ${{ matrix.api }}
          tag: google_apis
          abi: x86