name: pull_request-check
on: [ push, pull_request ]
jobs:
  detekt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: detekt
        run: |
          ./gradlew clean detekt

  sample-connectedCheck:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: connectedCheck
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew sample:connectedCheck

  kakao-library-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: kakao-library-build
        run: |
          ./gradlew kakao:build
